Upgrades

diff --git a/rpm/build b/rpm/build
--- a/rpm/build
+++ b/rpm/build
@@ -1,68 +1,95 @@
 #!/bin/bash -e
 
-MIRROR="http://mirrors.kernel.org/centos"
-BIGCOUCH_VERSION="0.4.0pre4"
+ARCHS="x86_64 i386"
+BIGCOUCH_VERSION="0.4.0pre5"
+DISTS="centos-6 centos-5"
 ERLANG_VERSION="otp_src_R14B01"
+MIRROR="http://mirrors.kernel.org/centos"
 
 # Install dependencies
-sudo apt-get install -y rpm yum > /dev/null
-
-# Configure web cache
-sudo apt-get -y install polipo > /dev/null
-export http_proxy="http://localhost:8123"
+sudo apt-get install -y rpm yum
 
 build() {
     DIR="`pwd`/chroots/centos-$1-$2"
     if [ "$2" == "i386" ]; then SETARCH="linux32"; else SETARCH="linux64"; fi
 
-    if [ ! -f "$DIR/etc/resolv.conf" ];
+    if [ ! -f "$DIR/.finished" ];
     then
         mkdir -p $DIR/etc
-        cat <<EOF > $DIR/etc/yum.conf
+        sudo cp /etc/resolv.conf $DIR/etc/
+        cat <<EOF | sudo tee $DIR/etc/yum.conf > /dev/null
 [main]
 distroverpkg=centos-release
-proxy=$http_proxy
-[base]
-name=base
-baseurl=$MIRROR/$1/os/$2/
-gpgcheck=0
-[update]
-name=updates
-baseurl=$MIRROR/$1/updates/$2/
 gpgcheck=0
 EOF
-        rpm --rebuilddb --root=$DIR > /dev/null
-        rm -f "$MIRROR/$4/$3"
-        wget "$MIRROR/$4/$3"
-        sudo rpm --install --force --root=$DIR --nodeps $3
-        sudo yum \
-            -c $DIR/etc/yum.conf \
-            --installroot=$DIR install -y \
+        $SETARCH rpm --rebuilddb --root=$DIR
+        wget -c "$MIRROR/$4/$3"
+        $SETARCH sudo rpm -i --nodeps --replacepkgs --root $DIR $3
+        $SETARCH sudo yum \
+            --installroot $DIR \
+            --nogpgcheck install -y \
             tar rpm-build yum
-        sudo cp /etc/resolv.conf $DIR/etc/
+        sudo touch "$DIR/.finished"
     fi
 
+    # Setup bind mounts
+    sudo mount --bind /proc $DIR/proc
+    sudo mount --bind /dev $DIR/dev
+    trap "sudo umount $DIR/proc; sudo umount $DIR/dev" EXIT
+
+    $SETARCH sudo chroot $DIR \
+        yum install -y tar rpm-build
+
     # Setup
-    sudo mkdir -p $DIR$HOME/rpmbuild/SOURCES
-    mkdir -p "${DIR}_result"
+    sudo mkdir -p $DIR$HOME/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
+    cat <<EOF | sudo tee $DIR$HOME/.rpmmacros > /dev/null
+%_topdir %(echo $HOME)/rpmbuild
+EOF
+    sudo mkdir -p "${DIR}_result"
 
-    # Build SpiderMonkey package
-    sudo cp js-1.8.5*.src.rpm $DIR$HOME
+    # Build SpiderMonkey package (disabled for now)
+    #if test -z "$(find ${DIR}_result -maxdepth 1 -name 'js-*.rpm' -print -quit)"
+    if test -z "DON'T BUILD"
+    then
+        $SETARCH sudo chroot $DIR yum install -y \
+            autoconf213 gcc gcc-c++ make nspr-devel \
+            python zip readline-devel ncurses-devel rpmlib \
+            pkgconfig
 
-    sudo chroot $DIR yum install -y \
-        autoconf213 gcc gcc-c++ make nspr-devel \
-        python zip readline-devel ncurses-devel rpmlib \
-        pkgconfig
+        sudo cp js.spec $DIR$HOME
+        sudo cp js*.patch js*.tar.gz $DIR$HOME/rpmbuild/SOURCES
+        $SETARCH sudo chroot $DIR rpmbuild -ba $HOME/js.spec
+        $SETARCH sudo chroot $DIR rpm --install --force --nodeps $HOME/rpmbuild/RPMS/$2/*.rpm
+    fi
 
-    $SETARCH sudo chroot $DIR rpmbuild --rebuild $HOME/js-1.8.5*.src.rpm
-    sudo rpm --install --force --root=$DIR --nodeps $DIR$HOME/rpmbuild/RPMS/$2/*.rpm
+    # Install js-devel if above build failed (or is disabled)
+    if test -z "$(find ${DIR}_result -maxdepth 1 -name 'js-*.rpm' -print -quit)"
+    then
+        EPEL_PATH="http://download.fedoraproject.org/pub/epel/$1/i386"
+        if [ "$1" == "5" ];
+        then
+            EPEL_NAME="epel-release-5-4.noarch.rpm"
+        elif [ "$1" == "6" ];
+        then
+            EPEL_NAME="epel-release-6-5.noarch.rpm"
+        else
+            echo "No EPEL found for $1"
+            exit
+        fi
+        wget -c $EPEL_PATH/$EPEL_NAME
+        $SETARCH sudo rpm --install --force --root=$DIR $EPEL_NAME
+        $SETARCH sudo chroot $DIR yum install -y js-devel
+    fi
 
     # Install erlang
-    sudo yum -c $DIR/etc/yum.conf --installroot=$DIR install -y \
-        java-1.6.0-openjdk libicu-devel openssl-devel libcurl-devel git
+    if test -z "$(find $DIR/usr/local/bin -maxdepth 1 -name 'erl' -print -quit)"
+    then
+        $SETARCH sudo chroot $DIR yum install -y \
+            make gcc gcc-c++ kernel-devel m4 ncurses-devel openssl-devel java-1.6.0-openjdk-devel \
+            python libicu-devel openssl-devel curl-devel git
 
-    sudo cp $ERLANG_VERSION.tar.gz $DIR$HOME
-    cat <<EOF > build_erlang
+        sudo cp $ERLANG_VERSION.tar.gz $DIR$HOME
+        cat <<EOF > build_erlang
 #!/bin/bash -e
 cd ~
 tar zxf $ERLANG_VERSION.tar.gz
@@ -75,30 +102,41 @@ cd $ERLANG_VERSION
 make
 make install
 EOF
-    chmod +x build_erlang
-    sudo cp build_erlang $DIR$HOME
-    sudo chroot $DIR ~/build_erlang
+        chmod +x build_erlang
+        sudo cp build_erlang $DIR$HOME
+        $SETARCH sudo chroot $DIR ~/build_erlang
+    fi
 
     # Build BigCouch package
-    sudo cp -f bigcouch.spec $DIR$HOME/
-    sudo cp -f bigcouch.tar.gz $DIR$HOME/rpmbuild/SOURCES/
-    $SETARCH sudo chroot $DIR rpmbuild -ba $HOME/bigcouch.spec \
-        --define "_revision 0.4.0" --define "_release 1"
+    if test -z "$(find ${DIR}_result -maxdepth 1 -name 'bigcouch-*.rpm' -print -quit)"
+    then
+        sudo cp -f bigcouch.spec $DIR$HOME/
+        sudo cp -f bigcouch.tar.gz $DIR$HOME/rpmbuild/SOURCES/
+        $SETARCH sudo GIT_SSL_NO_VERIFY=1 chroot $DIR rpmbuild -ba $HOME/bigcouch.spec \
+            --define "_revision $BIGCOUCH_VERSION" --define "_release 1"
+    fi
 
     # Extract RPM's
-    cp $DIR$HOME/rpmbuild/RPMS/$2/*.rpm "${DIR}_result/"
+    sudo cp $DIR$HOME/rpmbuild/RPMS/$2/*.rpm "${DIR}_result/"
+
+    # Remove bind mounts
+    sudo umount $DIR/proc
+    sudo umount $DIR/dev
+    trap - EXIT
 }
 
 js_src() {
-    rm -f js-1.8.5*.src.rpm
-    wget -c http://infrastructure.fedoraproject.org/repo/pub/fedora/linux/releases/16/Fedora/source/SRPMS/js-1.8.5-7.fc16.src.rpm
+    JS="js-1.8.5"
+    wget -c http://infrastructure.fedoraproject.org/repo/pub/fedora/linux/releases/16/Fedora/source/SRPMS/$JS-7.fc16.src.rpm
+    mkdir -p $JS
+    rpm2cpio $JS*.src.rpm | cpio -i
 }
 
 bigcouch_src() {
     rm -rf bigcouch
     mkdir -p bigcouch
     pushd bigcouch
-    wget -cO - https://github.com/cloudant/bigcouch/tarball/bigcouch-$BIGCOUCH_VERSION | tar xzf - --strip=1
+    wget -O - https://github.com/cloudant/bigcouch/tarball/bigcouch-$BIGCOUCH_VERSION | tar xzf - --strip=1
     git init
     git add `find . -maxdepth 1 -not -name debian`
     git commit -m "Tarball commit"
@@ -112,8 +150,7 @@ bigcouch_src() {
 }
 
 erlang_src() {
-    rm -rf $ERLANG_VERSION.tar.gz
-    wget http://erlang.org/download/$ERLANG_VERSION.tar.gz
+    wget -c http://erlang.org/download/$ERLANG_VERSION.tar.gz
 }
 
 js_src
@@ -122,8 +159,7 @@ erlang_src
 
 # Build all the things
 build "6" "x86_64" "centos-release-6-2.el6.centos.7.x86_64.rpm" "6/os/x86_64/Packages"
-build "6" "i386" "centos-release-6-2.el6.centos.7.i386.rpm" "6/os/i386/Packages"
+build "6" "i386" "centos-release-6-2.el6.centos.7.i686.rpm" "6/os/i386/Packages"
 
 build "5" "x86_64" "centos-release-5-7.el5.centos.x86_64.rpm" "5/os/x86_64/CentOS"
 build "5" "i386" "centos-release-5-7.el5.centos.i386.rpm" "5/os/i386/CentOS"
-
